In [13]:
import pandas as pd
df = pd.read_csv("../data/processed/edinet_analysis_data.csv")
df.head()

,company_name,business_description,business_risks,filename
0,テクミラホールディングス株式会社,3 事業の内容 当社グループは、テクミラホールディングス株式会社(当社)及び連結子会社9社、...,3 事業等のリスク 以下において、投資家に対する積極的な情報開示の観点から、当社グループの事...,S100VUJU.zip
1,IPSホールディングス株式会社,3 事業の内容 当社グループは、当社並びに連結子会社2社、非連結子会社1社、関連会社1社で構...,3 事業等のリスク 有価証券報告書に記載した事業の状況、経理の状況等に関する事項のうち、経営...,S100WRPN.zip
2,株式会社フォーバル・リアルストレート,3 事業の内容 当社は、企業のソリューションニーズが最も高まるオフィス移転時において、不動産...,3 事業等のリスク 当社の経営成績及び財政状態等に影響を及ぼす可能性のある主なリスクは以下の...,S100W4QO.zip
3,鷹之台ゴルフ株式会社,3 事業の内容 当社は、所有土地のすべてを一般社団法人鷹之台カンツリー倶楽部に賃貸しており、...,3 事業等のリスク 当社の売上高は、一般社団法人鷹之台カンツリー倶楽部へのゴルフ場用地の土地...,S100VWXC.zip
4,株式会社ジェーソン,3 事業の内容 当社グループの概要当社グループ(当社及び当社の関係会社)は、当社、連結子会社...,3 事業等のリスク 有価証券報告書に記載した事業の状況、経理の状況等に関する事項のうち、経営...,S100VUA9.zip

In [14]:
#サイズ（行列の数）の確認
df.shape

(4256, 4)

In [15]:
df.isnull().sum()
df_e = df[df["business_description"].isnull()]
df_e.sample(n=10, replace=True)

     company_name business_description business_risks      filename
253           NaN                  NaN            NaN  S100XCKJ.zip
223           NaN                  NaN            NaN  S100XCL5.zip
3123          NaN                  NaN            NaN  S100XCJV.zip
204           NaN                  NaN            NaN  S100XTG1.zip
3966          NaN                  NaN            NaN  S100VO82.zip
126           NaN                  NaN            NaN  S100XCK8.zip
3328          NaN                  NaN            NaN  S100XV05.zip
3144          NaN                  NaN            NaN  S100XCMC.zip
253           NaN                  NaN            NaN  S100XCKJ.zip
1939          NaN                  NaN            NaN  S100XUR4.zip

In [16]:
target_index = df[df['company_name'] == 'Zenken株式会社'].index
print(target_index)

RangeIndex(start=613, stop=614, step=1)

In [17]:
df.loc[613]

company_name                                                   Zenken株式会社
business_description                                                  NaN
business_risks          3 事業等のリスク 有価証券報告書に記載した事業の状況、経理の状況等に関する事項のうち、経営...
filename                                                     S100WQCF.zip
Name: 613, dtype: str

In [18]:
target_index = df[df['company_name'] == '株式会社フジクラ'].index
print(target_index)

RangeIndex(start=2853, stop=2854, step=1)

In [19]:
df.loc[2853]

company_name                                                     株式会社フジクラ
business_description    3 事業の内容 当社及び当社の関係会社は、(株)フジクラ(当社)、子会社108社及び関連会社...
business_risks          3 事業等のリスク 当社グループの経営成績、株価及び財務状況等に影響を及ぼす可能性のあるリス...
filename                                                     S100W6LJ.zip
Name: 2853, dtype: str

In [ ]:
from processor.edinet_process import clean_text
text = """３ 【事業の内容】当社グループは、当社、連結子会社１社、非連結子会社３社の計５社で構成されております。当社グループでは、グローバル・インバウンド（日本国内における国際化）に向けて、WEBマーケティング事業を中心とした「マーケティング」セグメント、海外のIT人材・介護人材を日本企業へ紹介等を行う人材事業と教育事業（語学研修・教育、留学斡旋等）を営む「海外人材」セグメント、保有不動産の賃貸事業を行う「不動産」セグメントの３つのセグメントにおいて事業展開を進めてまいりました。

 

(1) マーケティングセグメント
WEBマーケティング事業では、クライアントの特徴や強みを明らかにするWEBの集客メディアを制作・運用し、目的が明確な「意欲ある」ユーザーに訴求しております。当該ユーザーは、自らWEBでキーワード検索を行い、ユーザー自身の目的やニーズに合った商品・サービスに関する情報を収集しているため、コンバージョン※に至る可能性の高い見込み客であると想定されます。当社の提供するWEBの集客メディアは、クライアントに対して当該「意欲ある」ユーザーの送客を行うため、クライアントは自社の営業人員に頼らない効率的な営業活動が可能となると考えております。

当社が注力するBtoB業種では、日本中の中堅・中小企業がWEB上における“ニッチトップ”を確立し、その企業が提供するサービスや商材を必要とする顧客とのマッチングを促進させることで、日本経済の活性化に貢献します。例えば、「液体充填機」「攪拌脱泡機」「ハイスピードカメラ」など世の中に知られていないニッチな商材を扱う数多くの企業をWEBマーケティングの力によって、ユーザーニーズとクライアントの有するバリューを結び付け、コンバージョン見込みが高いユーザーを送客するメディアを運営しております。


※コンバージョン：消費者や見込み顧客が、商品の購入やサービスの加入などを行うこと

 

また、サービス提供体制として、専門的なメディアを「高品質」に制作する体制を構築しております。通常WEBサイト制作は、ディレクターが外部の業者に各工程を依頼・発注して制作しますが、当社では、コンサルティングから制作・編集・運用までをワンストップで提供できるサービス体制を構築しております。まず、コンサルティングでは、クライアントの競合優位性を顕在化させ、最適な市場のポジショニングをコンサルティングします。また、メディアの記事制作に関しては、これまで8,400メディア以上を制作・運用してきた豊富なノウハウの蓄積により、あらゆる業種に対応可能な制作体制を構築しております。更に、クライアントの業種に応じて関連法規に準拠しているか顧問弁護士指導のもとリーガルチェックを行う体制を構築しており、高品質のサービス提供体制を構築しております。メディアの運用に関しても、SEO※対策が必要ですが、常に変化する検索エンジンのアルゴリズムに対して柔軟かつ迅速に対応できるノウハウを長年のサービス提供を通じて蓄積していることも当社の特徴であると考えております。

※SEO（Search Engine Optimization）：検索エンジンの検索結果ページで、ホームページが表示される順位を上げる手法


 

上記サービス体制によるメディア制作費及び運用費を主な収益としまして、当連結会計年度におきましては、主に専門メディアの少ないニッチな市場（例えば、電機・機械等のBtoBの業種）向けを中心に293件（前期比48件増）のメディアを新規公開するとともに、978件（前期比８件増）のメディアを運用しております（平均継続期間43.6カ月）。

 

 


（主な関係会社）当社

 

(2) 海外人材セグメント
海外人材セグメントでは、主にIT・介護の海外人材の紹介や美容業界に特化した求人を紹介する「美プロ」などのメディアの運営等を行う人材事業のほか、法人向け語学研修や、留学斡旋、日本語教育等を行う教育事業を行っております。

 

① 人材事業
イ．海外IT人材事業

国内のIT人材は、2030年には最大で79万人、中位シナリオで約45万人（出所：経済産業省「IT人材需給に関する調査」（2019年３月））も人手が不足すると見込まれるほど人手不足が慢性化しております。そこで、インドのIT都市ベンガルールの上位大学と提携し（Indian Institute of Technology Hyderabad、R. V. College of Engineering、B.M.S. College of Engineering等）、ジャパンキャリアセンターを大学内に設け、インドでICT教育を受けて日本企業への就労を希望する学生と、IT人材不足に悩む日本の企業とのマッチングの機会を設けております。紹介手数料と、日本語教育料などを主な収益としております。

 

ロ．海外介護人材事業
日本の介護人材不足に対応するため、インドやインドネシアを中心とした特定技能人材の紹介と定着サポートを推進しております。定着率の課題解決を目指し、長く日本で働けるために必要な資格「介護福祉士」の資格取得を目指した５年間にわたる語学教育プログラム「ZENKEN NIHONGO 介護」の提供も行っております。また、2022年７月に譲受した埼玉県久喜市の介護施設を海外介護人材活用のロールモデルとすることを目指し、介護施設の運営も行っております。また、地方自治体との連携を進めており、鳥取県・茨城県・新潟県から外国人介護人材のマッチング支援や国家資格取得支援業務等を受託し、外国人介護人材の受け入れから定着まで一貫した支援体制を構築しております。紹介手数料と登録支援料、日本語教育料を主な収益としております。

 

ハ．その他

美容業界に特化した求人情報を紹介する「美プロ」などのメディアを運営しております。当事業は、クライアントからの各メディアへの広告料を主な収益としております。

 

② 教育事業

イ．法人向け語学研修事業

主に企業向けに、クライアントから受託した内容の語学研修を実施しております。TOEIC対策講座やビジネス英語講座、海外赴任直前の集中講座など、実務に必要な語学力を身につけるカリキュラムや教材、サービスメニューがあります。提供する講座内容は、大半を独自で開発し、講師を経験者に限定・事前に研修を受けることを条件に採用することで、品質の維持・向上に努めております。研修の形態も、オフィスや研修所に講師を派遣するスタイルのみならず、オンラインレッスン（Linguage Speak）等のクライアントのニーズに合わせた総合的なサービスを提供しております。その他、中学高校向けオンライン英会話も行っております。授業料と教材費を主な収益としております。

 

ロ．留学斡旋事業
当社は、アメリカ大学奨学金プログラム※のアジア総代理店として指名を受けて、米国の大学への正規留学を主軸に、海外の大学の学位取得等を目的とする留学を主に斡旋しております。

また、大学生を対象とした留学だけでなく、米国・カナダ・英国・オーストラリア・ニュージーランドへの正規高校留学や、米国の高校への交換留学、企業の若手・中堅社員を中心とした海外留学派遣のサポートも行っております。また、円安の影響もあり、マレーシアを軸とした東南アジアへの留学の需要も高まっており、アジアへの留学派遣にも注力しております。斡旋手数料を主な収益としております。

 

※アメリカ大学奨学金プログラム：アメリカ大学給付型奨学金留学プログラム（英語名：American University Scholarship Programs for Japanese Students)は、American Collegiate Scholarship Association を運営する 米国フロリダ州にあるInternational Doorways to Education & Athletics（IDEA）と米国大学スカラーシップ協会日本事務局を運営する当社がアメリカの大学で学ぶ留学生の支援を目的に実施するプログラムです。

 

ハ．日本語教育事業

法務省と文部科学省から正式認可を得て、2017年10月に新宿にリンゲージ日本語学校を開校いたしました。日本語を母国語としない外国人向けのプログラムで、“日本の企業で十分に就業できるレベル”までの教育を念頭に置いております。授業料を主な収益としております。

 

（主な関係会社）当社、全研ケア株式会社

 

(3) 不動産セグメント

当社が所有するオフィス用ビル「全研プラザ」及び「Zenken Plaza Ⅱ」の賃貸をしております。「全研プラザ」及び「Zenken Plaza Ⅱ」は、新宿駅から徒歩５分という好立地にあります。「全研プラザ」は、１階～10階の764坪をまとめて貸し出しております。また、「Zenken Plaza Ⅱ」は、１フロア約50坪のスペースを、10フロア分、貸し出すことが可能です。不動産賃料を主な収益としております。

 

（主な関係会社）当社

 

事業の系統図は、次のとおりであります。"""

new_text = clean_text(text)
print(new_text)

3 事業の内容 当社グループは、当社、連結子会社1社、非連結子会社3社の計5社で構成されております。当社グループでは、グローバル・インバウンド(日本国内における国際化)に向けて、WEBマーケティング事業を中心とした「マーケティング」セグメント、海外のIT人材・介護人材を日本企業へ紹介等を行う人材事業と教育事業(語学研修・教育、留学斡旋等)を営む「海外人材」セグメント、保有不動産の賃貸事業を行う「不動産」セグメントの3つのセグメントにおいて事業展開を進めてまいりました。 (1) マーケティングセグメント WEBマーケティング事業では、クライアントの特徴や強みを明らかにするWEBの集客メディアを制作・運用し、目的が明確な「意欲ある」ユーザーに訴求しております。当該ユーザーは、自らWEBでキーワード検索を行い、ユーザー自身の目的やニーズに合った商品・サービスに関する情報を収集しているため、コンバージョン に至る可能性の高い見込み客であると想定されます。当社の提供するWEBの集客メディアは、クライアントに対して当該「意欲ある」ユーザーの送客を行うため、クライアントは自社の営業人員に頼らない効率的な営業活動が可能となると考えております。 当社が注力するBtoB業種では、日本中の中堅・中小企業がWEB上における“ニッチトップ”を確立し、その企業が提供するサービスや商材を必要とする顧客とのマッチングを促進させることで、日本経済の活性化に貢献します。例えば、「液体充填機」「攪拌脱泡機」「ハイスピードカメラ」など世の中に知られていないニッチな商材を扱う数多くの企業をWEBマーケティングの力によって、ユーザーニーズとクライアントの有するバリューを結び付け、コンバージョン見込みが高いユーザーを送客するメディアを運営しております。 コンバージョン:消費者や見込み顧客が、商品の購入やサービスの加入などを行うこと また、サービス提供体制として、専門的なメディアを「高品質」に制作する体制を構築しております。通常WEBサイト制作は、ディレクターが外部の業者に各工程を依頼・発注して制作しますが、当社では、コンサルティングから制作・編集・運用までをワンストップで提供できるサービス体制を構築しております。まず、コンサルティングでは、クライアントの競合優位性を顕在化させ、最適な市場のポジショニングをコンサルティングします。また、メディアの記事制作に関しては、これまで8,400メディア以上を制作・運用してきた豊富なノウハウの蓄積により、あらゆる業種に対応可能な制作体制を構築しております。更に、クライアントの業種に応じて関連法規に準拠しているか顧問弁護士指導のもとリーガルチェックを行う体制を構築しており、高品質のサービス提供体制を構築しております。メディアの運用に関しても、SEO 対策が必要ですが、常に変化する検索エンジンのアルゴリズムに対して柔軟かつ迅速に対応できるノウハウを長年のサービス提供を通じて蓄積していることも当社の特徴であると考えております。 SEO(Search Engine Optimization):検索エンジンの検索結果ページで、ホームページが表示される順位を上げる手法 上記サービス体制によるメディア制作費及び運用費を主な収益としまして、当連結会計年度におきましては、主に専門メディアの少ないニッチな市場(例えば、電機・機械等のBtoBの業種)向けを中心に293件(前期比48件増)のメディアを新規公開するとともに、978件(前期比8件増)のメディアを運用しております(平均継続期間43.6カ月)。 (主な関係会社)当社 (2) 海外人材セグメント 海外人材セグメントでは、主にIT・介護の海外人材の紹介や美容業界に特化した求人を紹介する「美プロ」などのメディアの運営等を行う人材事業のほか、法人向け語学研修や、留学斡旋、日本語教育等を行う教育事業を行っております。 1 人材事業 イ.海外IT人材事業 国内のIT人材は、2030年には最大で79万人、中位シナリオで約45万人(出所:経済産業省「IT人材需給に関する調査」(2019年3月))も人手が不足すると見込まれるほど人手不足が慢性化しております。そこで、インドのIT都市ベンガルールの上位大学と提携し(Indian Institute of Technology Hyderabad、R. V. College of Engineering、B.M.S. College of Engineering等)、ジャパンキャリアセンターを大学内に設け、インドでICT教育を受けて日本企業への就労を希望する学生と、IT人材不足に悩む日本の企業とのマッチングの機会を設けております。紹介手数料と、日本語教育料などを主な収益としております。 ロ.海外介護人材事業 日本の介護人材不足に対応するため、インドやインドネシアを中心とした特定技能人材の紹介と定着サポートを推進しております。定着率の課題解決を目指し、長く日本で働けるために必要な資格「介護福祉士」の資格取得を目指した5年間にわたる語学教育プログラム「ZENKEN NIHONGO 介護」の提供も行っております。また、2022年7月に譲受した埼玉県久喜市の介護施設を海外介護人材活用のロールモデルとすることを目指し、介護施設の運営も行っております。また、地方自治体との連携を進めており、鳥取県・茨城県・新潟県から外国人介護人材のマッチング支援や国家資格取得支援業務等を受託し、外国人介護人材の受け入れから定着まで一貫した支援体制を構築しております。紹介手数料と登録支援料、日本語教育料を主な収益としております。 ハ.その他 美容業界に特化した求人情報を紹介する「美プロ」などのメディアを運営しております。当事業は、クライアントからの各メディアへの広告料を主な収益としております。 2 教育事業 イ.法人向け語学研修事業 主に企業向けに、クライアントから受託した内容の語学研修を実施しております。TOEIC対策講座やビジネス英語講座、海外赴任直前の集中講座など、実務に必要な語学力を身につけるカリキュラムや教材、サービスメニューがあります。提供する講座内容は、大半を独自で開発し、講師を経験者に限定・事前に研修を受けることを条件に採用することで、品質の維持・向上に努めております。研修の形態も、オフィスや研修所に講師を派遣するスタイルのみならず、オンラインレッスン(Linguage Speak)等のクライアントのニーズに合わせた総合的なサービスを提供しております。その他、中学高校向けオンライン英会話も行っております。授業料と教材費を主な収益としております。 ロ.留学斡旋事業 当社は、アメリカ大学奨学金プログラム のアジア総代理店として指名を受けて、米国の大学への正規留学を主軸に、海外の大学の学位取得等を目的とする留学を主に斡旋しております。 また、大学生を対象とした留学だけでなく、米国・カナダ・英国・オーストラリア・ニュージーランドへの正規高校留学や、米国の高校への交換留学、企業の若手・中堅社員を中心とした海外留学派遣のサポートも行っております。また、円安の影響もあり、マレーシアを軸とした東南アジアへの留学の需要も高まっており、アジアへの留学派遣にも注力しております。斡旋手数料を主な収益としております。 アメリカ大学奨学金プログラム:アメリカ大学給付型奨学金留学プログラム(英語名:American University Scholarship Programs for Japanese Students)は、American Collegiate Scholarship Association を運営する 米国フロリダ州にあるInternational Doorways to Education & Athletics(IDEA)と米国大学スカラーシップ協会日本事務局を運営する当社がアメリカの大学で学ぶ留学生の支援を目的に実施するプログラムです。 ハ.日本語教育事業 法務省と文部科学省から正式認可を得て、2017年10月に新宿にリンゲージ日本語学校を開校いたしました。日本語を母国語としない外国人向けのプログラムで、“日本の企業で十分に就業できるレベル”までの教育を念頭に置いております。授業料を主な収益としております。 (主な関係会社)当社、全研ケア株式会社 (3) 不動産セグメント 当社が所有するオフィス用ビル「全研プラザ」及び「Zenken Plaza II」の賃貸をしております。「全研プラザ」及び「Zenken Plaza II」は、新宿駅から徒歩5分という好立地にあります。「全研プラザ」は、1階~10階の764坪をまとめて貸し出しております。また、「Zenken Plaza II」は、1フロア約50坪のスペースを、10フロア分、貸し出すことが可能です。不動産賃料を主な収益としております。 (主な関係会社)当社 事業の系統図は、次のとおりであります。

In [21]:
df.loc[613, "business_description"] = new_text
df.loc[613]

company_name                                                   Zenken株式会社
business_description    3 事業の内容 当社グループは、当社、連結子会社1社、非連結子会社3社の計5社で構成されてお...
business_risks          3 事業等のリスク 有価証券報告書に記載した事業の状況、経理の状況等に関する事項のうち、経営...
filename                                                     S100WQCF.zip
Name: 613, dtype: str

In [22]:
df.isnull().sum()

company_name            27
business_description    27
business_risks          27
filename                 0
dtype: int64

In [23]:
df = df.dropna()
df.shape

(4229, 4)

In [24]:
df.to_csv("../data/processed/edinet_analysis_data_clns.csv", index=False, encoding="utf-8-sig")